version: 0.2

#env:
#  variables:
#    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#  parameter-store:
#    LOGIN_PASSWORD: "dockerLoginPassword"

phases:
  install:
    commands:
      - uname -a
      - echo $PATH

      # apt-get update -y is neccessary for install npm to work
      - apt-get update -y

      # I've switched image from java to node.js in hope weird error would disappeare, so I must install java manually
      # see https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04
      #- apt-get install openjdk-8-jdk

      #- apt-get install -y nodejs
      # instead link (see below) try legacy; should be before installing npm?
      - apt-get install -y nodejs-legacy

      - apt-get install -y npm
      - npm --version

      # disable https as workaroung for error "npm ERR! Error: CERT_UNTRUSTED" while installing bower
      - npm config set strict-ssl false

      # https://github.com/animetosho/Nyuu/issues/14#issue-202306091
      #- ln -s /usr/bin/nodejs /usr/bin/node


      # Someone says this must be run 2x
      - npm install -g npm
      - npm install -g npm

      - npm --version

      #- npm update
      #- npm --version
      # if image is node.js, shouldn't be npm already installed?

      # note to --no-bin-links
      # It is workaround for "npm WARN This failure might be due to the use of legacy binary "node" ... npm ERR! weird error 127"
      # see https://github.com/giseburt/TinyG-node/issues/4#issuecomment-286034755
      #- npm install -g bower
  pre_build:
    commands:
      - echo $PATH
      - find -name node
      - find / -name node
      #- npm install
cache:
  paths:
    # https://github.com/Idealstack/codebuild-example/blob/master/buildspec-2-caching.yml

    # Debian package caches, so we don't need to keep redownloading debian packages:
    - '/var/cache/apt/**/*'
    - '/var/lib/apt/lists/**/*'

    # Composer cache:
    #- /root/.composer/**/*

    # Node modules, if you need nodejs based tools like webpack during your build
    - '/root/.npm/**/*'
    - '/usr/lib/node_modules/**/*'